sources:
  - name: V2RA
    url: https://raw.githubusercontent.com/mahdibland/V2RayAggregator/refs/heads/master/Eternity.yml
    dedup: true

  - name: AMPN
    url: https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.yml

  - name: NMW
    url: https://raw.githubusercontent.com/peasoft/NoMoreWalls/refs/heads/master/list.yml