name: Update Clash Config

on:
  schedule:
    - cron: "0 0 * * *" # 每天 0 点运行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run script
        run: bash run.sh

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add output.yaml
          git commit -m "更新 Clash 配置文件"
          git push